/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import ListaCircularSimple2.Empleado;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;
import static Principal.Principal.*;
/**
 *
 * @author jimen
 */
public class FormRegistroEmpleados extends javax.swing.JFrame {

    Conexion cc = new Conexion();
    Connection  con = cc.conectar();

    public FormRegistroEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registrar Usuario");
    }
    
    public void prueba(){
        
        
    
    }
    public void agregaadministrador(){

    
    Random rnd = new Random();
        String abecedario = "ABCDEFGHIJKLMOPQRSTUVWXYZ";
        String cadena = "";
        String Codigo = "";
        int m = 0, pos = 0, num;
        while (m < 1) {
            pos = (int) (rnd.nextDouble() * abecedario.length() - 1 + 0);
            num = (int) (rnd.nextDouble() * 9999 + 1000);
            cadena = cadena + abecedario.charAt(pos) + num;
            pos = (int) (rnd.nextDouble() * abecedario.length()-1 + 0);
            cadena = cadena + abecedario.charAt(pos);
            Codigo = cadena;
            cadena = "";
            m++;
        }
    String cedula = String.valueOf(txtfieldcedula.getText());
    String telefono = String.valueOf(txtfieldtelefono.getText());
    String nombreempleado = txtfieldnombre1.getText();
    String sql = "insert into empleados (NombreEmpleado,Apellido1,Apellido2,Cedula,Telefono,Codigo) values (?,?,?,?,?,?) ";
     nuevalista2.insertarPrimero(new Empleado(nombreempleado)); 
    try{
        if (cedula.isEmpty() || telefono.isEmpty() || txtfieldapellido1.getText().isEmpty() || txtfieldapellido2.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "PORFAVOR RELLENE TODOS LOS CAMPOS", "", JOptionPane.WARNING_MESSAGE);
        }else{
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, txtfieldnombre1.getText());
            pst.setString(2, txtfieldapellido1.getText());
            pst.setString(3, txtfieldapellido2.getText());
            pst.setString(4, cedula);
            pst.setString(5, telefono);
            pst.setString(6, Codigo);
            pst.execute();
            limpiar();
            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
            JOptionPane.showMessageDialog(null, "CODIGO DE EMPLEADO: "+ " " +Codigo  +"\n" +"******NO OLVIDAR******");
        }
     
    }catch(Exception e){
    JOptionPane.showMessageDialog(null,"ERROR DE REGISTRO" + e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelobjetos = new javax.swing.JPanel();
        panelobjetosregistro = new javax.swing.JPanel();
        txtapellido1 = new javax.swing.JLabel();
        txtapellido2 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JLabel();
        txttelefono1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtfieldapellido1 = new javax.swing.JTextField();
        txtfieldapellido2 = new javax.swing.JTextField();
        txtfieldcedula = new javax.swing.JTextField();
        txtfieldtelefono = new javax.swing.JTextField();
        txtnombre1 = new javax.swing.JLabel();
        txtfieldnombre1 = new javax.swing.JTextField();
        panelboton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        imglogin = new javax.swing.JLabel();
        imgfondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelobjetos.setBackground(new java.awt.Color(41, 50, 60));
        panelobjetos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelobjetosregistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtapellido1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        txtapellido1.setForeground(new java.awt.Color(255, 255, 255));
        txtapellido1.setText("Apellido 1: ");
        panelobjetosregistro.add(txtapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        txtapellido2.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        txtapellido2.setForeground(new java.awt.Color(255, 255, 255));
        txtapellido2.setText("Apellido 2:");
        panelobjetosregistro.add(txtapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 20));

        txtcedula.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        txtcedula.setForeground(new java.awt.Color(255, 255, 255));
        txtcedula.setText("Cedula:");
        panelobjetosregistro.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 70, 20));

        txttelefono1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        txttelefono1.setForeground(new java.awt.Color(255, 255, 255));
        txttelefono1.setText("Telefono:");
        panelobjetosregistro.add(txttelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 20));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE EMPLEADO");
        panelobjetosregistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, -1));

        txtfieldapellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldapellido1ActionPerformed(evt);
            }
        });
        panelobjetosregistro.add(txtfieldapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, -1));
        panelobjetosregistro.add(txtfieldapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, -1));
        panelobjetosregistro.add(txtfieldcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 150, -1));
        panelobjetosregistro.add(txtfieldtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        txtnombre1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        txtnombre1.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre1.setText("Nombre:");
        panelobjetosregistro.add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));
        panelobjetosregistro.add(txtfieldnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, -1));

        panelboton.setBackground(new java.awt.Color(64, 104, 151));
        panelboton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelboton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("   REGISTRAR");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        panelboton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        panelobjetosregistro.add(panelboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 130, 30));

        imglogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginfinal.jpg"))); // NOI18N
        panelobjetosregistro.add(imglogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        panelobjetos.add(panelobjetosregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 400, 370));

        imgfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iguanaimg.jpg"))); // NOI18N
        panelobjetos.add(imgfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 510));

        PanelPrincipal.add(panelobjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1030, 510));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HEALTHYBONES VETERYNARY");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logofinal.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        PanelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
        txtfieldnombre1.setText("");
        txtfieldapellido1.setText("");        
        txtfieldapellido2.setText("");
        txtfieldcedula.setText("");
        txtfieldtelefono.setText("");
    }
    private void txtfieldapellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldapellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldapellido1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        agregaadministrador();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        FormAdministracion run = new FormAdministracion();
        run.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        IniciaSesion run = new IniciaSesion();
       run.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistroEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel imgfondo;
    private javax.swing.JLabel imglogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelboton;
    private javax.swing.JPanel panelobjetos;
    private javax.swing.JPanel panelobjetosregistro;
    private javax.swing.JLabel txtapellido1;
    private javax.swing.JLabel txtapellido2;
    private javax.swing.JLabel txtcedula;
    private javax.swing.JTextField txtfieldapellido1;
    private javax.swing.JTextField txtfieldapellido2;
    private javax.swing.JTextField txtfieldcedula;
    private javax.swing.JTextField txtfieldnombre1;
    private javax.swing.JTextField txtfieldtelefono;
    private javax.swing.JLabel txtnombre1;
    private javax.swing.JLabel txttelefono1;
    // End of variables declaration//GEN-END:variables
}
